# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-30 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('file_name', models.CharField(max_length=100)),
                ('image_size', models.IntegerField(max_length=8)),
                ('image_path', models.CharField(max_length=100)),
                ('image_type', models.CharField(max_length=20)),
                ('save_file_name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'timer_image',
            },
        ),
        migrations.CreateModel(
            name='TImageRel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('business_id', models.BigIntegerField(max_length=20)),
                ('business_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'timer_image_rel',
            },
        ),
        migrations.CreateModel(
            name='TLabel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'timer_label',
            },
        ),
        migrations.CreateModel(
            name='TPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('p_name', models.CharField(max_length=50)),
                ('p_phone', models.CharField(max_length=50)),
                ('p_email', models.EmailField(max_length=100)),
                ('p_sex', models.IntegerField(max_length=1)),
            ],
            options={
                'db_table': 'timer_person',
            },
        ),
        migrations.CreateModel(
            name='TPersonSite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sitId', models.BigIntegerField(max_length=20)),
            ],
            options={
                'db_table': 'timer_person_site',
            },
        ),
        migrations.CreateModel(
            name='TSite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site_url', models.CharField(max_length=200)),
                ('site_desc', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'timer_site',
            },
        ),
    ]
