# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-30 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnav', '0002_auto_20180130_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tperson',
            name='p_email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tperson',
            name='p_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tperson',
            name='p_phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tperson',
            name='p_sex',
            field=models.IntegerField(max_length=1, null=True),
        ),
    ]
