# Generated by Django 2.0.1 on 2018-01-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnav', '0003_auto_20180130_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='timagerel',
            name='image_id',
            field=models.BigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tperson',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tperson',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsite',
            name='offer_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsite',
            name='offerer_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsite',
            name='offerer_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tsite',
            name='site_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timage',
            name='file_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timage',
            name='image_path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timage',
            name='image_size',
            field=models.IntegerField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='timage',
            name='image_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='timage',
            name='save_file_name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='timagerel',
            name='business_id',
            field=models.BigIntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='timagerel',
            name='business_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tlabel',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tlabel',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tsite',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tsite',
            name='site_desc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tsite',
            name='site_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
