# Generated by Django 2.0.1 on 2018-01-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnav', '0004_auto_20180131_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timage',
            name='image_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timagerel',
            name='business_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timagerel',
            name='image_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tpersonsite',
            name='sitId',
            field=models.BigIntegerField(),
        ),
    ]
