# Generated by Django 2.0.1 on 2018-01-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnav', '0005_auto_20180131_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tperson',
            name='p_sex',
            field=models.IntegerField(null=True),
        ),
    ]
